"""Initial schema

Revision ID: f5312e8d14c4
Revises: 
Create Date: 2026-07-30 16:56:31.350817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5312e8d14c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_domain', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), server_default='freemium', nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('notification_email', sa.String(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('primary_domain', name=op.f('uq_organizations_primary_domain'))
    )
    op.create_table('assets',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('whitelisted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assets_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('org_id', 'value', name=op.f('uq_assets_org_id'))
    )
    op.create_table('audit_log',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_log_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('members',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), server_default='owner', nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_members_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('org_id', 'user_id', name=op.f('uq_members_org_id'))
    )
    op.create_table('scans',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='queued', nullable=False),
    sa.Column('scan_type', sa.String(), server_default='full', nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('findings_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('langgraph_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(), server_default='scheduled', nullable=False),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_scans_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_table('compliance_reports',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_compliance_reports_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_compliance_reports_scan_id_scans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_reports'))
    )
    op.create_table('findings',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('finding_type', sa.String(), nullable=False),
    sa.Column('agent_source', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plain_explanation', sa.String(), nullable=True),
    sa.Column('remediation_steps', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('false_positive_reason', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_findings_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_findings_scan_id_scans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_table('notifications',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='sent', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_notifications_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_notifications_scan_id_scans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('findings')
    op.drop_table('compliance_reports')
    op.drop_table('scans')
    op.drop_table('members')
    op.drop_table('audit_log')
    op.drop_table('assets')
    op.drop_table('organizations')
    # ### end Alembic commands ###
